"""API and helpers for React frontend runtime."""

from __future__ import annotations

from pathlib import Path
from typing import Any
from urllib.parse import parse_qs, urlparse

from flask import Blueprint, current_app, jsonify, request, send_file, send_from_directory
from werkzeug.exceptions import NotFound

from core.auth import get_current_user, is_auth_disabled, is_authenticated, is_login_configured, require_auth_json
from core.react_frontend.api_catalog import build_api_catalog


api_react_frontend = Blueprint('api_react_frontend', __name__, url_prefix='/api/frontend')
REACT_DIST_URL_PREFIX = '/frontend-dist'

VALID_SETTINGS_VIEWS = {'target', 'system'}

DEFAULT_OPTIONS_TABS = {
    'email': True,
    'extranotifs': True,
    'telegram': True,
    'webhook': True,
    'powerflow': True,
    'options': True,
    'database': True,
    'log': True,
    'advanced': True,
    'renamer': True,
    'operations': True,
    'admin': True,
    'about': True,
}


def _react_index_path() -> Path:
    """Resolve built React index path inside frontend dist folder."""
    return _react_dist_root() / 'index.html'


def _react_dist_root() -> Path:
    """Resolve frontend dist root generated by Vite."""
    return Path(current_app.root_path) / 'frontend' / 'app' / 'dist'


def _is_react_bundle_available() -> bool:
    index_path = _react_index_path()
    return index_path.exists() and index_path.is_file()


def _safe_monitoring_state() -> dict[str, Any]:
    """Build monitoring runtime payload for frontend bootstrap."""
    state: dict[str, Any] = {
        'monitoring_profile': 'single',
        'multi_nut_enabled': False,
        'multi_nut_target_count': 0,
        'active_target_id': None,
        'active_target': None,
    }

    try:
        from core.multi_nut.polling import get_multi_nut_runtime_state

        runtime_state = get_multi_nut_runtime_state()
        profile = str(runtime_state.get('monitoring_profile') or 'single').strip().lower()
        if profile not in {'single', 'multi'}:
            profile = 'single'

        state['monitoring_profile'] = profile
        state['multi_nut_enabled'] = profile == 'multi' and bool(runtime_state.get('multi_enabled', False))
        state['multi_nut_target_count'] = int(runtime_state.get('enabled_targets', 0) or 0)
    except Exception:
        return state

    if state['multi_nut_target_count'] <= 0:
        return state

    try:
        from core.multi_nut.active_target import get_active_target, get_request_or_active_target_id

        state['active_target_id'] = get_request_or_active_target_id()
        state['active_target'] = get_active_target()
    except Exception:
        pass

    return state


def _safe_runtime_payload() -> dict[str, Any]:
    """Read app runtime status if helper is available."""
    payload = {
        'status': 'unconfigured',
        'message': '',
        'updated_at': '',
    }

    runtime_getter = getattr(current_app, 'get_runtime_state', None)
    if callable(runtime_getter):
        try:
            runtime_state = runtime_getter()
            payload['status'] = str(runtime_state.get('status') or payload['status'])
            payload['message'] = str(runtime_state.get('message') or '')
            payload['updated_at'] = str(runtime_state.get('updated_at') or '')
        except Exception:
            pass
    return payload


def _resolve_requested_settings_view() -> str:
    """Resolve requested settings view from explicit query or encoded path."""
    requested_view = str(request.args.get('view') or '').strip().lower()
    if requested_view in VALID_SETTINGS_VIEWS:
        return requested_view

    encoded_path = str(request.args.get('path') or '').strip()
    if encoded_path:
        try:
            parsed_query = parse_qs(urlparse(encoded_path).query or '')
            candidate = str((parsed_query.get('view') or [''])[0]).strip().lower()
            if candidate in VALID_SETTINGS_VIEWS:
                return candidate
        except Exception:
            pass

    return 'target'


def _safe_user_options_payload() -> dict[str, Any]:
    """Return settings tab visibility payload for current user."""
    current_user = get_current_user() or {}

    if is_auth_disabled():
        return {
            'settings_view': _resolve_requested_settings_view(),
            'is_admin': True,
            'options_tabs': dict(DEFAULT_OPTIONS_TABS),
        }

    payload = {
        'settings_view': _resolve_requested_settings_view(),
        'is_admin': False,
        'options_tabs': {
            **DEFAULT_OPTIONS_TABS,
            'options': False,
            'advanced': False,
            'renamer': False,
            'operations': False,
            'admin': False,
        },
    }

    try:
        from core import auth as auth_module

        login_model = getattr(auth_module, 'LoginAuth', None)
        user_id = current_user.get('id')
        if not login_model or not user_id:
            role = str(current_user.get('role') or '').strip().lower()
            if role == 'administrator':
                payload['is_admin'] = True
                payload['options_tabs'] = dict(DEFAULT_OPTIONS_TABS)
            return payload

        user = login_model.query.filter_by(id=int(user_id), is_active=True).first()
        if not user:
            return payload

        role = str(getattr(user, 'role', '')).strip().lower()
        is_admin = bool(getattr(user, 'is_admin', False)) or role == 'administrator'
        payload['is_admin'] = is_admin

        if is_admin:
            payload['options_tabs'] = dict(DEFAULT_OPTIONS_TABS)
            return payload

        if hasattr(user, 'get_options_tabs'):
            options_tabs = user.get_options_tabs() or {}
            normalized = {}
            for key in DEFAULT_OPTIONS_TABS.keys():
                if key == 'about':
                    normalized[key] = True
                else:
                    normalized[key] = bool(options_tabs.get(key, False))
            payload['options_tabs'] = normalized
    except Exception:
        pass

    return payload


def _react_bundle_error_response():
    return (
        "React UI build not found. Run: "
        "cd nutify/frontend/app && npm install && npm run build",
        503,
        {'Content-Type': 'text/plain; charset=utf-8'},
    )


def serve_react_index():
    """Serve React SPA entrypoint if build exists, otherwise show clear error."""
    index_path = _react_index_path()
    if _is_react_bundle_available():
        return send_file(index_path)

    return _react_bundle_error_response()


def serve_react_dist_asset(asset_path: str):
    """Serve built React assets from frontend dist directory."""
    dist_root = _react_dist_root()
    if not dist_root.exists():
        return _react_bundle_error_response()

    try:
        return send_from_directory(dist_root, asset_path)
    except NotFound:
        return ('React asset not found', 404, {'Content-Type': 'text/plain; charset=utf-8'})


@api_react_frontend.route('/bootstrap', methods=['GET'])
def frontend_bootstrap():
    """Return frontend bootstrap payload for React runtime."""
    monitoring = _safe_monitoring_state()
    runtime = _safe_runtime_payload()
    timezone_name = getattr(getattr(current_app, 'CACHE_TIMEZONE', None), 'zone', 'UTC')
    settings_context = _safe_user_options_payload()
    current_user = get_current_user()
    if isinstance(current_user, dict):
        current_user = {
            **current_user,
            'is_admin': bool(settings_context.get('is_admin', False)),
            'options_tabs': settings_context.get('options_tabs', {}),
        }

    return jsonify(
        {
            'success': True,
            'data': {
                'route': request.path,
                'request_path': request.args.get('path') or request.path,
                'timezone': timezone_name,
                'auth': {
                    'configured': bool(is_login_configured()),
                    'authenticated': bool(is_authenticated()),
                    'disabled': bool(is_auth_disabled()),
                    'current_user': current_user,
                },
                'runtime': runtime,
                'monitoring': monitoring,
                'settings': settings_context,
                'react_bundle_available': _is_react_bundle_available(),
            },
        }
    )


@api_react_frontend.route('/catalog', methods=['GET'])
@require_auth_json
def frontend_api_catalog():
    """Return a live catalog of registered API routes for the hidden docs page."""
    return jsonify(
        {
            'success': True,
            'data': build_api_catalog(),
        }
    )


def register_react_frontend_api(app):
    """Register React frontend helper API blueprint."""
    if api_react_frontend.name not in app.blueprints:
        app.register_blueprint(api_react_frontend)

    if 'react_frontend_dist_asset' not in app.view_functions:
        app.add_url_rule(
            f'{REACT_DIST_URL_PREFIX}/<path:asset_path>',
            endpoint='react_frontend_dist_asset',
            view_func=serve_react_dist_asset,
            methods=['GET'],
        )
