"""API endpoints to generate per-target external NOTIFYCMD scripts."""

from __future__ import annotations

import re
from urllib.parse import urlsplit

from flask import Blueprint, current_app, jsonify, request

from core.auth import require_admin
from core.events.callback_token import ensure_event_api_token

from .storage import get_target_with_policy


api_notifycmd_script = Blueprint(
    'api_notifycmd_script',
    __name__,
    url_prefix='/api/multi-nut',
)


def _json_error(message: str, status: int = 400):
    return jsonify({'success': False, 'error': message}), status


def _extract_host_context() -> tuple[str, str, str]:
    """Extract scheme/host/port from current request with safe defaults."""
    raw_scheme = (request.scheme or 'http').strip().lower()
    scheme = raw_scheme if raw_scheme in {'http', 'https'} else 'http'

    parsed = urlsplit(f"//{request.host}", scheme=scheme)
    host = (parsed.hostname or '127.0.0.1').strip() or '127.0.0.1'

    if parsed.port:
        port = str(parsed.port)
    else:
        port = '443' if scheme == 'https' else '5050'

    return scheme, host, port


def _build_notifycmd_script(
    *,
    target_id: int,
    target_name: str,
    ups_name: str,
    ups_host: str,
    ups_port: int,
    destination_ip: str,
    destination_port: str,
    destination_scheme: str,
    api_token: str,
) -> str:
    """Return a standalone bash script for remote NUT hosts."""
    safe_target_name = (target_name or '').replace('"', '\\"')
    safe_ups_name = (ups_name or '').replace('"', '\\"')
    safe_ups_host = (ups_host or '').replace('"', '\\"')
    safe_api_token = (api_token or '').replace('\\', '\\\\').replace('"', '\\"')

    return f"""#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# Nutify external NOTIFYCMD bridge
# -----------------------------------------------------------------------------
# This script is generated by Nutify for one monitored UPS target.
#
# Purpose:
# - Receive UPS notification events from a remote NUT host (upsmon NOTIFYCMD)
# - Forward those events to this Nutify instance over HTTP
# - Preserve target identity (target_id) so Nutify routes notifications correctly
#
# How to use on the remote NUT host:
# 1) Copy this file to a stable path, for example:
#      /etc/nut/nutify_notifycmd_target_{target_id}.sh
# 2) Make it executable:
#      chmod +x /etc/nut/nutify_notifycmd_target_{target_id}.sh
# 3) Set in upsmon.conf:
#      NOTIFYCMD /etc/nut/nutify_notifycmd_target_{target_id}.sh
# 4) Reload/restart NUT monitor service.
#
# Notes:
# - All variables below are editable.
# - DESTINATION_IP must point to the Nutify server reachable by this host.
# - The script intentionally never blocks upsmon: on network errors it exits 0.
# -----------------------------------------------------------------------------

set -u

# Nutify server destination (edit if needed).
DESTINATION_SCHEME="{destination_scheme}"
DESTINATION_IP="{destination_ip}"
DESTINATION_PORT="{destination_port}"
API_PATH="/api/nut_event"

# Target identity in Nutify (do not change unless you remap targets).
TARGET_ID="{target_id}"
TARGET_NAME="{safe_target_name}"
UPS_NAME="{safe_ups_name}"
UPS_HOST="{safe_ups_host}"
UPS_PORT="{ups_port}"

# Callback token used by Nutify server-side validation.
# NOTE: this value is plain text inside this script file by design.
# Nutify stores the authoritative token server-side and validates header
# X-Nutify-Token on /api/nut_event callbacks.
# Protect script permissions (chmod 700 / owner-only) on remote hosts.
API_TOKEN="{safe_api_token}"

# Resolve the event type from upsmon context.
# upsmon exports NOTIFYTYPE; we keep positional args as fallback.
EVENT_TYPE="${{NOTIFYTYPE:-${{1:-UNKNOWN}}}}"

# Resolve UPS identifier from upsmon context.
# UPSNAME is exported by upsmon in most setups.
UPS_IDENTIFIER="${{UPSNAME:-${{2:-${{UPS_NAME}}@${{UPS_HOST}}:${{UPS_PORT}}}}}}"

# Build a deterministic UTC timestamp for auditing.
EVENT_TIMESTAMP_UTC="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# Escape a value for safe inline JSON string composition.
json_escape() {{
  printf '%s' "$1" | sed -e 's/\\\\/\\\\\\\\/g' -e 's/"/\\\\\\"/g'
}}

ESC_EVENT_TYPE="$(json_escape "$EVENT_TYPE")"
ESC_UPS_IDENTIFIER="$(json_escape "$UPS_IDENTIFIER")"
ESC_TARGET_NAME="$(json_escape "$TARGET_NAME")"
ESC_UPS_NAME="$(json_escape "$UPS_NAME")"
ESC_UPS_HOST="$(json_escape "$UPS_HOST")"
ESC_TIMESTAMP="$(json_escape "$EVENT_TIMESTAMP_UTC")"

# Compose minimal Nutify payload understood by /api/nut_event.
PAYLOAD="{{\\"ups\\":\\"${{ESC_UPS_IDENTIFIER}}\\",\\"event\\":\\"${{ESC_EVENT_TYPE}}\\",\\"target_id\\":${{TARGET_ID}},\\"target_name\\":\\"${{ESC_TARGET_NAME}}\\",\\"ups_name\\":\\"${{ESC_UPS_NAME}}\\",\\"host\\":\\"${{ESC_UPS_HOST}}\\",\\"timestamp_utc\\":\\"${{ESC_TIMESTAMP}}\\"}}"

# Build destination URL.
DESTINATION_URL="${{DESTINATION_SCHEME}}://${{DESTINATION_IP}}:${{DESTINATION_PORT}}${{API_PATH}}"

# Forward event to Nutify.
# Failures are logged locally but do not break the calling upsmon process.
if [ -n "$API_TOKEN" ]; then
  curl --silent --show-error --max-time 8 \\
    --request POST \\
    --header "Content-Type: application/json" \\
    --header "X-Nutify-Token: $API_TOKEN" \\
    --data "$PAYLOAD" \\
    "$DESTINATION_URL" >/dev/null 2>&1 || logger -t nutify-notifycmd "Forward failed for target $TARGET_ID event $EVENT_TYPE"
else
  curl --silent --show-error --max-time 8 \\
    --request POST \\
    --header "Content-Type: application/json" \\
    --data "$PAYLOAD" \\
    "$DESTINATION_URL" >/dev/null 2>&1 || logger -t nutify-notifycmd "Forward failed for target $TARGET_ID event $EVENT_TYPE"
fi

# Never propagate failure to upsmon.
# IMPORTANT: upsmon must include +EXEC in NOTIFYFLAG lines, otherwise
# NOTIFYCMD is not executed for that event type.
# Recommended flags:
#   NOTIFYFLAG ONLINE   SYSLOG+WALL+EXEC
#   NOTIFYFLAG ONBATT   SYSLOG+WALL+EXEC
#   NOTIFYFLAG LOWBATT  SYSLOG+WALL+EXEC
#   NOTIFYFLAG FSD      SYSLOG+WALL+EXEC
#   NOTIFYFLAG COMMOK   SYSLOG+WALL+EXEC
#   NOTIFYFLAG COMMBAD  SYSLOG+WALL+EXEC
#   NOTIFYFLAG SHUTDOWN SYSLOG+WALL+EXEC
#   NOTIFYFLAG REPLBATT SYSLOG+WALL+EXEC
#   NOTIFYFLAG NOCOMM   SYSLOG+WALL+EXEC
#   NOTIFYFLAG NOPARENT SYSLOG+WALL+EXEC
exit 0
"""


@api_notifycmd_script.route('/targets/<int:target_id>/notifycmd-script', methods=['GET'])
@require_admin
def download_notifycmd_script(target_id: int):
    """Download generated NOTIFYCMD bridge script for one target."""
    target, _policy = get_target_with_policy(target_id)
    if not target:
        return _json_error('Target not found', 404)

    scheme, detected_host, detected_port = _extract_host_context()
    destination_ip = str(request.args.get('destination_ip', detected_host) or detected_host).strip()
    destination_port = str(request.args.get('destination_port', detected_port) or detected_port).strip()
    destination_scheme = str(request.args.get('destination_scheme', scheme) or scheme).strip().lower()

    if not destination_ip:
        return _json_error('destination_ip is required', 400)
    if destination_scheme not in {'http', 'https'}:
        return _json_error('destination_scheme must be http or https', 400)

    api_token = ensure_event_api_token()
    if not api_token:
        return _json_error('Could not initialize callback token', 500)

    script_body = _build_notifycmd_script(
        target_id=int(target.id),
        target_name=str(target.name or ''),
        ups_name=str(target.ups_name or ''),
        ups_host=str(target.host or ''),
        ups_port=int(target.port or 3493),
        destination_ip=destination_ip,
        destination_port=destination_port,
        destination_scheme=destination_scheme,
        api_token=api_token,
    )

    safe_name = re.sub(r'[^a-zA-Z0-9._-]+', '_', str(target.name or 'target')).strip('_') or 'target'
    filename = f"nutify_notifycmd_target_{int(target.id)}_{safe_name}.sh"
    response = current_app.response_class(
        response=script_body,
        status=200,
        mimetype='text/x-shellscript',
    )
    response.headers['Content-Disposition'] = f'attachment; filename={filename}'
    return response


def register_api_routes(app):
    """Register NOTIFYCMD script API blueprint."""
    if api_notifycmd_script.name not in app.blueprints:
        app.register_blueprint(api_notifycmd_script)
