// @ts-nocheck

function queryElement(id: string) {
  return document.getElementById(id)
}

function createWizardRuntimeElements() {
  return {
    prevBtn: queryElement('prev-btn'),
    wizardExtraActions: queryElement('wizard-extra-actions'),
    nextBtn: queryElement('next-btn'),
    saveBtn: queryElement('save-btn'),
    testConfigBtn: queryElement('test-config-btn'),
    restartBtn: queryElement('restart-btn'),
    restartServerBtn: queryElement('restart-server-btn'),
    steps: document.querySelectorAll('.step'),
    stepContents: document.querySelectorAll('.wizard-step-content'),
    primaryModeOptions: document.querySelectorAll('.primary-mode-option'),
    topologyOptions: document.querySelectorAll('.topology-option'),
    hostModeOptions: document.querySelectorAll('.host-mode-option'),
    profileOptions: document.querySelectorAll('.profile-option'),
    configTabs: document.querySelectorAll('.config-tab'),
    configPreview: queryElement('config-preview'),
    alertsContainer: queryElement('alerts-container'),
    singleProfileHint: queryElement('single-profile-hint'),
    multiProfileHint: queryElement('multi-profile-hint'),
    serverNameField: queryElement('server_name'),
    multiTargetsSection: queryElement('multi-targets-section'),
    primaryTargetWorkflow: queryElement('primary-target-workflow'),
    primaryTargetTestSaveBtn: queryElement('primary-target-test-save-btn'),
    primaryTargetWorkflowStatus: queryElement('primary-target-workflow-status'),
    primaryConfigSummaryStandalone: queryElement('primary-config-summary-standalone'),
    primaryConfigSummaryNetserver: queryElement('primary-config-summary-netserver'),
    singleModeSelection: queryElement('single-mode-selection'),
    multiTopologySelection: queryElement('multi-topology-selection'),
    multiHostServiceSelection: queryElement('multi-host-service-selection'),
    multiDerivedHostMode: queryElement('multi-derived-host-mode'),
    scanStandaloneBtn: queryElement('scan-standalone'),
    scanNetserverBtn: queryElement('scan-netserver'),
    manualStandaloneRadio: queryElement('manual-standalone'),
    autoStandaloneRadio: queryElement('auto-standalone'),
    manualNetserverRadio: queryElement('manual-netserver'),
    autoNetserverRadio: queryElement('auto-netserver'),
    standaloneDriverSelect: queryElement('ups_driver'),
    netserverDriverSelect: queryElement('server_ups_driver'),
    standalonePortInput: queryElement('ups_port'),
    netserverPortInput: queryElement('server_ups_port'),
    standaloneUsbPortPicker: queryElement('standalone-usb-port-picker'),
    netserverUsbPortPicker: queryElement('netserver-usb-port-picker'),
    standaloneDetectedUsbPortSelect: queryElement('standalone_detected_usb_port'),
    netserverDetectedUsbPortSelect: queryElement('netserver_detected_usb_port'),
    standaloneUsbPortRefreshBtn: queryElement('scan-standalone-usb-ports'),
    netserverUsbPortRefreshBtn: queryElement('scan-netserver-usb-ports'),
    standaloneUsbPortPickerHelp: queryElement('standalone-usb-port-picker-help'),
    netserverUsbPortPickerHelp: queryElement('netserver-usb-port-picker-help'),
    standaloneSnmpFields: queryElement('standalone-snmp-fields'),
    netserverSnmpFields: queryElement('netserver-snmp-fields'),
    standaloneSnmpCommunity: queryElement('snmp_community'),
    standaloneSnmpVersion: queryElement('snmp_version'),
    netserverSnmpCommunity: queryElement('server_snmp_community'),
    netserverSnmpVersion: queryElement('server_snmp_version'),
    standaloneTimezone: queryElement('ups_timezone'),
    standaloneCurrency: queryElement('ups_currency'),
    standalonePollingInterval: queryElement('ups_polling_interval'),
    standaloneTargetDisplayName: queryElement('ups_target_display_name'),
    netserverTimezone: queryElement('server_timezone'),
    netserverCurrency: queryElement('server_currency'),
    netserverPollingInterval: queryElement('server_polling_interval'),
    netserverTargetDisplayName: queryElement('server_target_display_name'),
    netclientTimezone: queryElement('remote_timezone'),
    netclientCurrency: queryElement('remote_currency'),
    netclientTargetDisplayName: queryElement('remote_target_display_name'),
    netclientPollingInterval: queryElement('remote_polling_interval'),
    netclientLocationEnabled: queryElement('remote_location_enabled'),
    netclientLocation: queryElement('remote_location'),
    netclientLocationCountry: queryElement('remote_location_country'),
    netclientLocationRegion: queryElement('remote_location_region'),
    netclientLocationCity: queryElement('remote_location_city'),
    netclientLocationPostalCode: queryElement('remote_location_postal_code'),
    netclientLocationAddress: queryElement('remote_location_address'),
    netclientLocationFields: queryElement('remote-location-fields'),
    editConfigBtn: queryElement('edit-config-btn'),
    configEditorContainer: queryElement('config-editor-container'),
    configPreviewElement: queryElement('config-preview'),
    editorActions: queryElement('editor-actions'),
    saveEditBtn: queryElement('save-edit-btn'),
    cancelEditBtn: queryElement('cancel-edit-btn'),
    modal: queryElement('test-modal'),
    modalClose: queryElement('test-modal-close'),
    closeModalBtn: queryElement('close-modal-btn'),
    testMessage: queryElement('test-message'),
    multiTargetTestList: queryElement('multi-target-test-list'),
    upscOutput: queryElement('upsc-output'),
    missingRealpowerForm: queryElement('missing-realpower-form'),
    realpowerInput: queryElement('ups-realpower-nominal'),
    targetDetailModal: queryElement('target-detail-modal'),
    targetDetailModalClose: queryElement('target-detail-modal-close'),
    targetDetailCloseBtn: queryElement('target-detail-close-btn'),
    targetDetailTitle: queryElement('target-detail-title'),
    targetDetailMessage: queryElement('target-detail-message'),
    targetDetailOutput: queryElement('target-detail-output'),
    nominalPowerModal: queryElement('nominal-power-modal'),
    nominalPowerModalClose: queryElement('nominal-power-modal-close'),
    nominalPowerModalCancelBtn: queryElement('nominal-power-modal-cancel-btn'),
    nominalPowerModalSaveBtn: queryElement('nominal-power-modal-save-btn'),
    nominalPowerModalInput: queryElement('nominal-power-modal-input'),
    nominalPowerModalMessage: queryElement('nominal-power-modal-message'),
    multiTargetName: queryElement('multi_target_name'),
    multiTargetUpsName: queryElement('multi_target_ups_name'),
    multiTargetConnectionType: queryElement('multi_target_connection_type'),
    multiTargetConnectionTypeGroup: queryElement('multi-target-connection-type-group'),
    multiTargetHost: queryElement('multi_target_host'),
    multiTargetPort: queryElement('multi_target_port'),
    multiTargetMonitorUsername: queryElement('multi_target_monitor_username'),
    multiTargetMonitorPassword: queryElement('multi_target_monitor_password'),
    multiTargetLocalDriver: queryElement('multi_target_local_driver'),
    multiTargetLocalPort: queryElement('multi_target_local_port'),
    multiTargetUsbPortPicker: queryElement('multi-target-usb-port-picker'),
    multiTargetDetectedUsbPortSelect: queryElement('multi_target_detected_usb_port'),
    multiTargetUsbPortRefreshBtn: queryElement('scan-multi-target-usb-ports'),
    multiTargetUsbPortPickerHelp: queryElement('multi-target-usb-port-picker-help'),
    multiTargetLocalDesc: queryElement('multi_target_local_desc'),
    multiTargetTimezone: queryElement('multi_target_timezone'),
    multiTargetCurrency: queryElement('multi_target_currency'),
    multiTargetSnmpFields: queryElement('multi-target-snmp-fields'),
    multiTargetSnmpCommunity: queryElement('multi_target_snmp_community'),
    multiTargetSnmpVersion: queryElement('multi_target_snmp_version'),
    multiTargetPolling: queryElement('multi_target_polling_interval'),
    multiTargetDbStrategy: queryElement('multi_target_db_strategy'),
    multiTargetShardGroup: queryElement('multi-target-shard-group'),
    multiTargetShard: queryElement('multi_target_shard_granularity'),
    multiTargetNotifyScope: queryElement('multi_target_notify_scope'),
    multiTargetSeparateDbPathGroup: queryElement('multi-target-separate-db-path-group'),
    multiTargetSeparateDbPath: queryElement('multi_target_separate_db_path'),
    multiTargetEnabled: queryElement('multi_target_enabled'),
    multiTargetPrimary: queryElement('multi_target_primary'),
    multiTargetLocationEnabled: queryElement('multi_target_location_enabled'),
    multiTargetLocation: queryElement('multi_target_location'),
    multiTargetLocationCountry: queryElement('multi_target_location_country'),
    multiTargetLocationRegion: queryElement('multi_target_location_region'),
    multiTargetLocationCity: queryElement('multi_target_location_city'),
    multiTargetLocationPostalCode: queryElement('multi_target_location_postal_code'),
    multiTargetLocationAddress: queryElement('multi_target_location_address'),
    multiTargetLocationSuggestions: queryElement('multi-target-location-suggestions'),
    multiTargetTestBtn: queryElement('multi-target-test-btn'),
    multiTargetAddBtn: queryElement('multi-target-add-btn'),
    multiTargetResetBtn: queryElement('multi-target-reset-btn'),
    multiTargetTestStatus: queryElement('multi-target-test-status'),
    multiTargetFlowHint: queryElement('multi-target-flow-hint'),
    multiTargetProgress: queryElement('multi-target-progress'),
    multiTargetsList: queryElement('multi-targets-list'),
    multiTargetsEmpty: queryElement('multi-targets-empty'),
    multiTargetRemoteFields: queryElement('multi-target-remote-fields'),
    multiTargetLocalFields: queryElement('multi-target-local-fields'),
    multiTargetLocationFields: queryElement('multi-target-location-fields'),
    stepTitle: queryElement('step-title'),
  }
}

export function createWizardRuntimeContext() {
  const setupContainer = document.querySelector('.setup-container')
  if (!setupContainer) {
    return null
  }

  const authDisabled = setupContainer?.dataset.authDisabled === 'true'
  const firstStep = authDisabled ? 2 : 1

  return {
    setupContainer,
    elements: createWizardRuntimeElements(),
    state: {
      authDisabled,
      firstStep,
      currentStep: firstStep,
      selectedMode: null,
      selectedProfile: 'single',
      selectedTopology: null,
      selectedHostServiceMode: 'standalone',
      configData: null,
      configFiles: {},
      editedFiles: {},
      currentFile: null,
      editor: null,
      upsRealpowerNominal: null,
      multiTargets: [],
      editingMultiTargetIndex: -1,
      lastTargetTestSignature: null,
      lastTargetTestConnectionSignature: null,
      lastTargetTestSuccess: false,
      primaryTargetPrepared: false,
      primaryNextStepUnlocked: false,
      primaryTargetNominalPower: null,
      multiTargetDraftNominalPower: null,
      multiTargetDraftLocationLatitude: null,
      multiTargetDraftLocationLongitude: null,
      pendingNominalPowerResolver: null,
      locationSuggestionDebounceTimer: null,
      locationSuggestionsAbortController: null,
      locationSuggestionRequestId: 0,
      manualUsbDevicesByMode: {},
      manualUsbSelectedDeviceByMode: {},
      autoDetectedDeviceByMode: {},
      multiTargetUsbDevices: null,
      multiTargetSelectedUsbDevice: null,
    },
    actions: {},
  }
}

export function refreshWizardRuntimeElements(ctx) {
  Object.assign(ctx.elements, createWizardRuntimeElements())
}
